/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SKILLDotmdRouteImport } from './routes/SKILL[.]md'
import { Route as RULESDotmdRouteImport } from './routes/RULES[.]md'
import { Route as HEARTBEATDotmdRouteImport } from './routes/HEARTBEAT[.]md'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContractsIndexRouteImport } from './routes/contracts/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as DocsSetupRouteImport } from './routes/docs/setup'
import { Route as ContractsIdRouteImport } from './routes/contracts/$id'
import { Route as AgentsIdRouteImport } from './routes/agents/$id'
import { Route as ApiV1DeploymentsIndexRouteImport } from './routes/api/v1/deployments/index'
import { Route as ApiV1StatsOverviewRouteImport } from './routes/api/v1/stats/overview'
import { Route as ApiV1StatsAgentsRouteImport } from './routes/api/v1/stats/agents'
import { Route as ApiV1DeploymentsFeaturedRouteImport } from './routes/api/v1/deployments/featured'
import { Route as ApiV1DeploymentsIdRouteImport } from './routes/api/v1/deployments/$id'
import { Route as ApiV1AgentsRotateKeyRouteImport } from './routes/api/v1/agents/rotate-key'
import { Route as ApiV1AgentsRegisterRouteImport } from './routes/api/v1/agents/register'
import { Route as ApiV1AgentsIdRouteImport } from './routes/api/v1/agents/$id'
import { Route as ApiV1DeploymentsVerifiedIndexRouteImport } from './routes/api/v1/deployments/verified/index'
import { Route as ApiV1DeploymentsIdInteractRouteImport } from './routes/api/v1/deployments/$id/interact'
import { Route as ApiV1DeploymentsIdAbiRouteImport } from './routes/api/v1/deployments/$id/abi'
import { Route as ApiV1AgentsIdDeploymentsRouteImport } from './routes/api/v1/agents/$id/deployments'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SKILLDotmdRoute = SKILLDotmdRouteImport.update({
  id: '/SKILL.md',
  path: '/SKILL.md',
  getParentRoute: () => rootRouteImport,
} as any)
const RULESDotmdRoute = RULESDotmdRouteImport.update({
  id: '/RULES.md',
  path: '/RULES.md',
  getParentRoute: () => rootRouteImport,
} as any)
const HEARTBEATDotmdRoute = HEARTBEATDotmdRouteImport.update({
  id: '/HEARTBEAT.md',
  path: '/HEARTBEAT.md',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsIndexRoute = ContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSetupRoute = DocsSetupRouteImport.update({
  id: '/docs/setup',
  path: '/docs/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsIdRoute = ContractsIdRouteImport.update({
  id: '/contracts/$id',
  path: '/contracts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIdRoute = AgentsIdRouteImport.update({
  id: '/agents/$id',
  path: '/agents/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DeploymentsIndexRoute = ApiV1DeploymentsIndexRouteImport.update({
  id: '/api/v1/deployments/',
  path: '/api/v1/deployments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1StatsOverviewRoute = ApiV1StatsOverviewRouteImport.update({
  id: '/api/v1/stats/overview',
  path: '/api/v1/stats/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1StatsAgentsRoute = ApiV1StatsAgentsRouteImport.update({
  id: '/api/v1/stats/agents',
  path: '/api/v1/stats/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DeploymentsFeaturedRoute =
  ApiV1DeploymentsFeaturedRouteImport.update({
    id: '/api/v1/deployments/featured',
    path: '/api/v1/deployments/featured',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1DeploymentsIdRoute = ApiV1DeploymentsIdRouteImport.update({
  id: '/api/v1/deployments/$id',
  path: '/api/v1/deployments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AgentsRotateKeyRoute = ApiV1AgentsRotateKeyRouteImport.update({
  id: '/api/v1/agents/rotate-key',
  path: '/api/v1/agents/rotate-key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AgentsRegisterRoute = ApiV1AgentsRegisterRouteImport.update({
  id: '/api/v1/agents/register',
  path: '/api/v1/agents/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AgentsIdRoute = ApiV1AgentsIdRouteImport.update({
  id: '/api/v1/agents/$id',
  path: '/api/v1/agents/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DeploymentsVerifiedIndexRoute =
  ApiV1DeploymentsVerifiedIndexRouteImport.update({
    id: '/api/v1/deployments/verified/',
    path: '/api/v1/deployments/verified/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1DeploymentsIdInteractRoute =
  ApiV1DeploymentsIdInteractRouteImport.update({
    id: '/interact',
    path: '/interact',
    getParentRoute: () => ApiV1DeploymentsIdRoute,
  } as any)
const ApiV1DeploymentsIdAbiRoute = ApiV1DeploymentsIdAbiRouteImport.update({
  id: '/abi',
  path: '/abi',
  getParentRoute: () => ApiV1DeploymentsIdRoute,
} as any)
const ApiV1AgentsIdDeploymentsRoute =
  ApiV1AgentsIdDeploymentsRouteImport.update({
    id: '/deployments',
    path: '/deployments',
    getParentRoute: () => ApiV1AgentsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/HEARTBEAT.md': typeof HEARTBEATDotmdRoute
  '/RULES.md': typeof RULESDotmdRoute
  '/SKILL.md': typeof SKILLDotmdRoute
  '/stats': typeof StatsRoute
  '/agents/$id': typeof AgentsIdRoute
  '/contracts/$id': typeof ContractsIdRoute
  '/docs/setup': typeof DocsSetupRoute
  '/agents/': typeof AgentsIndexRoute
  '/contracts/': typeof ContractsIndexRoute
  '/api/v1/agents/$id': typeof ApiV1AgentsIdRouteWithChildren
  '/api/v1/agents/register': typeof ApiV1AgentsRegisterRoute
  '/api/v1/agents/rotate-key': typeof ApiV1AgentsRotateKeyRoute
  '/api/v1/deployments/$id': typeof ApiV1DeploymentsIdRouteWithChildren
  '/api/v1/deployments/featured': typeof ApiV1DeploymentsFeaturedRoute
  '/api/v1/stats/agents': typeof ApiV1StatsAgentsRoute
  '/api/v1/stats/overview': typeof ApiV1StatsOverviewRoute
  '/api/v1/deployments/': typeof ApiV1DeploymentsIndexRoute
  '/api/v1/agents/$id/deployments': typeof ApiV1AgentsIdDeploymentsRoute
  '/api/v1/deployments/$id/abi': typeof ApiV1DeploymentsIdAbiRoute
  '/api/v1/deployments/$id/interact': typeof ApiV1DeploymentsIdInteractRoute
  '/api/v1/deployments/verified/': typeof ApiV1DeploymentsVerifiedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/HEARTBEAT.md': typeof HEARTBEATDotmdRoute
  '/RULES.md': typeof RULESDotmdRoute
  '/SKILL.md': typeof SKILLDotmdRoute
  '/stats': typeof StatsRoute
  '/agents/$id': typeof AgentsIdRoute
  '/contracts/$id': typeof ContractsIdRoute
  '/docs/setup': typeof DocsSetupRoute
  '/agents': typeof AgentsIndexRoute
  '/contracts': typeof ContractsIndexRoute
  '/api/v1/agents/$id': typeof ApiV1AgentsIdRouteWithChildren
  '/api/v1/agents/register': typeof ApiV1AgentsRegisterRoute
  '/api/v1/agents/rotate-key': typeof ApiV1AgentsRotateKeyRoute
  '/api/v1/deployments/$id': typeof ApiV1DeploymentsIdRouteWithChildren
  '/api/v1/deployments/featured': typeof ApiV1DeploymentsFeaturedRoute
  '/api/v1/stats/agents': typeof ApiV1StatsAgentsRoute
  '/api/v1/stats/overview': typeof ApiV1StatsOverviewRoute
  '/api/v1/deployments': typeof ApiV1DeploymentsIndexRoute
  '/api/v1/agents/$id/deployments': typeof ApiV1AgentsIdDeploymentsRoute
  '/api/v1/deployments/$id/abi': typeof ApiV1DeploymentsIdAbiRoute
  '/api/v1/deployments/$id/interact': typeof ApiV1DeploymentsIdInteractRoute
  '/api/v1/deployments/verified': typeof ApiV1DeploymentsVerifiedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/HEARTBEAT.md': typeof HEARTBEATDotmdRoute
  '/RULES.md': typeof RULESDotmdRoute
  '/SKILL.md': typeof SKILLDotmdRoute
  '/stats': typeof StatsRoute
  '/agents/$id': typeof AgentsIdRoute
  '/contracts/$id': typeof ContractsIdRoute
  '/docs/setup': typeof DocsSetupRoute
  '/agents/': typeof AgentsIndexRoute
  '/contracts/': typeof ContractsIndexRoute
  '/api/v1/agents/$id': typeof ApiV1AgentsIdRouteWithChildren
  '/api/v1/agents/register': typeof ApiV1AgentsRegisterRoute
  '/api/v1/agents/rotate-key': typeof ApiV1AgentsRotateKeyRoute
  '/api/v1/deployments/$id': typeof ApiV1DeploymentsIdRouteWithChildren
  '/api/v1/deployments/featured': typeof ApiV1DeploymentsFeaturedRoute
  '/api/v1/stats/agents': typeof ApiV1StatsAgentsRoute
  '/api/v1/stats/overview': typeof ApiV1StatsOverviewRoute
  '/api/v1/deployments/': typeof ApiV1DeploymentsIndexRoute
  '/api/v1/agents/$id/deployments': typeof ApiV1AgentsIdDeploymentsRoute
  '/api/v1/deployments/$id/abi': typeof ApiV1DeploymentsIdAbiRoute
  '/api/v1/deployments/$id/interact': typeof ApiV1DeploymentsIdInteractRoute
  '/api/v1/deployments/verified/': typeof ApiV1DeploymentsVerifiedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/HEARTBEAT.md'
    | '/RULES.md'
    | '/SKILL.md'
    | '/stats'
    | '/agents/$id'
    | '/contracts/$id'
    | '/docs/setup'
    | '/agents/'
    | '/contracts/'
    | '/api/v1/agents/$id'
    | '/api/v1/agents/register'
    | '/api/v1/agents/rotate-key'
    | '/api/v1/deployments/$id'
    | '/api/v1/deployments/featured'
    | '/api/v1/stats/agents'
    | '/api/v1/stats/overview'
    | '/api/v1/deployments/'
    | '/api/v1/agents/$id/deployments'
    | '/api/v1/deployments/$id/abi'
    | '/api/v1/deployments/$id/interact'
    | '/api/v1/deployments/verified/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/HEARTBEAT.md'
    | '/RULES.md'
    | '/SKILL.md'
    | '/stats'
    | '/agents/$id'
    | '/contracts/$id'
    | '/docs/setup'
    | '/agents'
    | '/contracts'
    | '/api/v1/agents/$id'
    | '/api/v1/agents/register'
    | '/api/v1/agents/rotate-key'
    | '/api/v1/deployments/$id'
    | '/api/v1/deployments/featured'
    | '/api/v1/stats/agents'
    | '/api/v1/stats/overview'
    | '/api/v1/deployments'
    | '/api/v1/agents/$id/deployments'
    | '/api/v1/deployments/$id/abi'
    | '/api/v1/deployments/$id/interact'
    | '/api/v1/deployments/verified'
  id:
    | '__root__'
    | '/'
    | '/HEARTBEAT.md'
    | '/RULES.md'
    | '/SKILL.md'
    | '/stats'
    | '/agents/$id'
    | '/contracts/$id'
    | '/docs/setup'
    | '/agents/'
    | '/contracts/'
    | '/api/v1/agents/$id'
    | '/api/v1/agents/register'
    | '/api/v1/agents/rotate-key'
    | '/api/v1/deployments/$id'
    | '/api/v1/deployments/featured'
    | '/api/v1/stats/agents'
    | '/api/v1/stats/overview'
    | '/api/v1/deployments/'
    | '/api/v1/agents/$id/deployments'
    | '/api/v1/deployments/$id/abi'
    | '/api/v1/deployments/$id/interact'
    | '/api/v1/deployments/verified/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HEARTBEATDotmdRoute: typeof HEARTBEATDotmdRoute
  RULESDotmdRoute: typeof RULESDotmdRoute
  SKILLDotmdRoute: typeof SKILLDotmdRoute
  StatsRoute: typeof StatsRoute
  AgentsIdRoute: typeof AgentsIdRoute
  ContractsIdRoute: typeof ContractsIdRoute
  DocsSetupRoute: typeof DocsSetupRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  ContractsIndexRoute: typeof ContractsIndexRoute
  ApiV1AgentsIdRoute: typeof ApiV1AgentsIdRouteWithChildren
  ApiV1AgentsRegisterRoute: typeof ApiV1AgentsRegisterRoute
  ApiV1AgentsRotateKeyRoute: typeof ApiV1AgentsRotateKeyRoute
  ApiV1DeploymentsIdRoute: typeof ApiV1DeploymentsIdRouteWithChildren
  ApiV1DeploymentsFeaturedRoute: typeof ApiV1DeploymentsFeaturedRoute
  ApiV1StatsAgentsRoute: typeof ApiV1StatsAgentsRoute
  ApiV1StatsOverviewRoute: typeof ApiV1StatsOverviewRoute
  ApiV1DeploymentsIndexRoute: typeof ApiV1DeploymentsIndexRoute
  ApiV1DeploymentsVerifiedIndexRoute: typeof ApiV1DeploymentsVerifiedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/SKILL.md': {
      id: '/SKILL.md'
      path: '/SKILL.md'
      fullPath: '/SKILL.md'
      preLoaderRoute: typeof SKILLDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/RULES.md': {
      id: '/RULES.md'
      path: '/RULES.md'
      fullPath: '/RULES.md'
      preLoaderRoute: typeof RULESDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/HEARTBEAT.md': {
      id: '/HEARTBEAT.md'
      path: '/HEARTBEAT.md'
      fullPath: '/HEARTBEAT.md'
      preLoaderRoute: typeof HEARTBEATDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts/': {
      id: '/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof ContractsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/setup': {
      id: '/docs/setup'
      path: '/docs/setup'
      fullPath: '/docs/setup'
      preLoaderRoute: typeof DocsSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts/$id': {
      id: '/contracts/$id'
      path: '/contracts/$id'
      fullPath: '/contracts/$id'
      preLoaderRoute: typeof ContractsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$id': {
      id: '/agents/$id'
      path: '/agents/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AgentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/deployments/': {
      id: '/api/v1/deployments/'
      path: '/api/v1/deployments'
      fullPath: '/api/v1/deployments/'
      preLoaderRoute: typeof ApiV1DeploymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/stats/overview': {
      id: '/api/v1/stats/overview'
      path: '/api/v1/stats/overview'
      fullPath: '/api/v1/stats/overview'
      preLoaderRoute: typeof ApiV1StatsOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/stats/agents': {
      id: '/api/v1/stats/agents'
      path: '/api/v1/stats/agents'
      fullPath: '/api/v1/stats/agents'
      preLoaderRoute: typeof ApiV1StatsAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/deployments/featured': {
      id: '/api/v1/deployments/featured'
      path: '/api/v1/deployments/featured'
      fullPath: '/api/v1/deployments/featured'
      preLoaderRoute: typeof ApiV1DeploymentsFeaturedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/deployments/$id': {
      id: '/api/v1/deployments/$id'
      path: '/api/v1/deployments/$id'
      fullPath: '/api/v1/deployments/$id'
      preLoaderRoute: typeof ApiV1DeploymentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/agents/rotate-key': {
      id: '/api/v1/agents/rotate-key'
      path: '/api/v1/agents/rotate-key'
      fullPath: '/api/v1/agents/rotate-key'
      preLoaderRoute: typeof ApiV1AgentsRotateKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/agents/register': {
      id: '/api/v1/agents/register'
      path: '/api/v1/agents/register'
      fullPath: '/api/v1/agents/register'
      preLoaderRoute: typeof ApiV1AgentsRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/agents/$id': {
      id: '/api/v1/agents/$id'
      path: '/api/v1/agents/$id'
      fullPath: '/api/v1/agents/$id'
      preLoaderRoute: typeof ApiV1AgentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/deployments/verified/': {
      id: '/api/v1/deployments/verified/'
      path: '/api/v1/deployments/verified'
      fullPath: '/api/v1/deployments/verified/'
      preLoaderRoute: typeof ApiV1DeploymentsVerifiedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/deployments/$id/interact': {
      id: '/api/v1/deployments/$id/interact'
      path: '/interact'
      fullPath: '/api/v1/deployments/$id/interact'
      preLoaderRoute: typeof ApiV1DeploymentsIdInteractRouteImport
      parentRoute: typeof ApiV1DeploymentsIdRoute
    }
    '/api/v1/deployments/$id/abi': {
      id: '/api/v1/deployments/$id/abi'
      path: '/abi'
      fullPath: '/api/v1/deployments/$id/abi'
      preLoaderRoute: typeof ApiV1DeploymentsIdAbiRouteImport
      parentRoute: typeof ApiV1DeploymentsIdRoute
    }
    '/api/v1/agents/$id/deployments': {
      id: '/api/v1/agents/$id/deployments'
      path: '/deployments'
      fullPath: '/api/v1/agents/$id/deployments'
      preLoaderRoute: typeof ApiV1AgentsIdDeploymentsRouteImport
      parentRoute: typeof ApiV1AgentsIdRoute
    }
  }
}

interface ApiV1AgentsIdRouteChildren {
  ApiV1AgentsIdDeploymentsRoute: typeof ApiV1AgentsIdDeploymentsRoute
}

const ApiV1AgentsIdRouteChildren: ApiV1AgentsIdRouteChildren = {
  ApiV1AgentsIdDeploymentsRoute: ApiV1AgentsIdDeploymentsRoute,
}

const ApiV1AgentsIdRouteWithChildren = ApiV1AgentsIdRoute._addFileChildren(
  ApiV1AgentsIdRouteChildren,
)

interface ApiV1DeploymentsIdRouteChildren {
  ApiV1DeploymentsIdAbiRoute: typeof ApiV1DeploymentsIdAbiRoute
  ApiV1DeploymentsIdInteractRoute: typeof ApiV1DeploymentsIdInteractRoute
}

const ApiV1DeploymentsIdRouteChildren: ApiV1DeploymentsIdRouteChildren = {
  ApiV1DeploymentsIdAbiRoute: ApiV1DeploymentsIdAbiRoute,
  ApiV1DeploymentsIdInteractRoute: ApiV1DeploymentsIdInteractRoute,
}

const ApiV1DeploymentsIdRouteWithChildren =
  ApiV1DeploymentsIdRoute._addFileChildren(ApiV1DeploymentsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HEARTBEATDotmdRoute: HEARTBEATDotmdRoute,
  RULESDotmdRoute: RULESDotmdRoute,
  SKILLDotmdRoute: SKILLDotmdRoute,
  StatsRoute: StatsRoute,
  AgentsIdRoute: AgentsIdRoute,
  ContractsIdRoute: ContractsIdRoute,
  DocsSetupRoute: DocsSetupRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  ContractsIndexRoute: ContractsIndexRoute,
  ApiV1AgentsIdRoute: ApiV1AgentsIdRouteWithChildren,
  ApiV1AgentsRegisterRoute: ApiV1AgentsRegisterRoute,
  ApiV1AgentsRotateKeyRoute: ApiV1AgentsRotateKeyRoute,
  ApiV1DeploymentsIdRoute: ApiV1DeploymentsIdRouteWithChildren,
  ApiV1DeploymentsFeaturedRoute: ApiV1DeploymentsFeaturedRoute,
  ApiV1StatsAgentsRoute: ApiV1StatsAgentsRoute,
  ApiV1StatsOverviewRoute: ApiV1StatsOverviewRoute,
  ApiV1DeploymentsIndexRoute: ApiV1DeploymentsIndexRoute,
  ApiV1DeploymentsVerifiedIndexRoute: ApiV1DeploymentsVerifiedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
